TEMP_DIRS=incremental-tmp.* incremental-backup *.tplm *.tppt
TEMP_FILES=models corpora *.lock dev1_* lm.incremental_fr cpt.incremental.en2fr \
           log.* dev1.out.* s1.out* s1.rules
include ../Makefile.incl
