#!/bin/bash
# Sample Subsequent Boot Script; see section 5 of PLiveVA.pdf for documentation.

# Un comment to send the output of this script to a logfile
#exec > /opt/vmware/var/log/subsequentboot 2>&1

# 5.1 Replace a placeholder with the current IP of the VA
sed "s/__REPLACE_THIS_WITH_YOUR_IP__/`ifconfig | grep \"inet addr\" | head -1 | awk {'print $2'} | cut -d \":\" -f2`/" /opt/Portage/www/PortageLiveAPI.wsdl > /var/www/html/PortageLiveAPI.wsdl
sed "s/__REPLACE_THIS_WITH_YOUR_IP__/`ifconfig | grep \"inet addr\" | head -1 | awk {'print $2'} | cut -d \":\" -f2`/" /opt/Portage/www/secure/PortageLiveAPI.wsdl > /var/www/html/secure/PortageLiveAPI.wsdl

