# Makefile for basic textutils
#
# @author Eric Joanis
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2010, Sa Majeste la Reine du Chef du Canada /
# Copyright 2010, Her Majesty in Right of Canada

PROGRAMS = \
	asciify \
	get_voc \
	strip_non_printing \
	utf8_casemap \
	utf8_filter

DYNLIBS= $(LIBICU)

BINSCRIPTS = $(wildcard *.sh *.pl *.py) \
	select-line

include ../build/Makefile.incl
