#!/bin/bash
# $Id$
#############################################################
#
# @file postdecode_plugin
# @brief Default post-decoder plugin
#
# @author Michel Simard
#
# COMMENTS:
#
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2010, Conseil national de recherches du Canada /
# Copyright 2010, National Research Council of Canada
#############################################################

## 
## Usage: postdecode_plugin < in > out
## 
## Default postdecoding plugin: to be called immediately after decoding.
##

# WARNING: postdecode_plugin must not change the tokenization of the text
#          because the truecasing process uses phrase alignment information
#          from the decoder, which will be wrong if the tokenization changes.
#          Also, the input to the postdecode_plugin may contain XML markup
#          identifying OOVs.

if [ "$1" == "-help" -o "$1" == "-h" ]; then
    cat $0 | grep "^##" | cut -c4-
    exit 1
fi

exec cat
