#!/bin/bash
# $Id$
#############################################################
#
# @file postprocess_plugin
# @brief Default post-processor plugin
#
# @author Michel Simard
#
# COMMENTS:
#
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2010, Conseil national de recherches du Canada /
# Copyright 2010, National Research Council of Canada
#############################################################

## 
## Usage: postprocess_plugin TGT_LANG < in > out
## 
## Default postprocessing plugin: to be called after detokenization.
##

if [ "$1" == "-help" -o "$1" == "-h" ]; then
    cat $0 | grep "^##" | cut -c4-
    exit 1
fi

test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
TARGET_LANGUAGE=$1; shift

# Suggestion: for an English->French system, you could use fix-en-fr-numbers.pl
# to patch numbers, reformatting them from English to French style.
# Uncomment the following line to activate:
#fix-en-fr-numbers.pl |

# Suggestion: for French, some punctuation is best separated by non-breakable spaces.
# Careful: the space between the quotes after nbsp is a non-breaking space, not
# a regular one.  Make sure it's still an NBSP if you cut and paste this
# anywhere...
# Uncomment the following block of lines to activate, and modify to suit your
# needs; you can leave lines that don't apply to you in comments.
#perl -pe 'BEGIN{ use encoding "UTF-8"; use utf8; $nbsp = " "; $nbhy = "\x{2011}"; }
#          s/ ([:»%\$])/$nbsp$1/g;    # Makes space before :, », % and $ non-breakable
#          s/([«]) /$1$nbsp/g;        # Makes space after « non-breakable
#          s/ (V|volts)\b/$nbsp$1/g;  # Makes space before V or volts non-breakable
#          s/\b(A)-(2)\b/$1$nbhy$2/g; # Makes hyphen in A-2 non-breakable
#         ' |

# Default is to just copy the input to the output.
cat
