#!/bin/bash
#
# @file postprocess_plugin
# @brief Default post-processor plugin
#
# @author Michel Simard
#
# COMMENTS:
#
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2010, Conseil national de recherches du Canada /
# Copyright 2010, National Research Council of Canada

## 
## Usage: postprocess_plugin TGT_LANG < in > out
## 
## Default postprocessing plugin: to be called after detokenization.
##

if [ "$1" == "-help" -o "$1" == "-h" ]; then
    cat $0 | grep "^##" | cut -c4-
    exit 1
fi

test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
TARGET_LANGUAGE=$1; shift

# Suggestion: for an English->French system, you could use fix-en-fr-numbers.pl
# to patch numbers, reformatting them from English to French style.
# Uncomment the following line to activate:
#fix-en-fr-numbers.pl |

# Suggestion: for French, some punctuation is best separated by non-breakable spaces.
# Careful: the space between the quotes after nbsp is a non-breaking space, not
# a regular one.  Make sure it's still an NBSP if you cut and paste this
# anywhere...
# Uncomment the following block of lines to activate, and modify to suit your
# needs; you can leave lines that don't apply to you in comments.
#perl -pe 'BEGIN{ use encoding "UTF-8"; use utf8;
#             $nbsp = " "; # There is a literal non-break space, \xA0, in the quotes here
#             # Choose only one of the following non-break hyphen definitions:
#             $nbhy = "\x{2011}";   # This is the unicode non-break hyphen
#             $nbhy = "\x1E";       # This is the old MS Word non-break hyphen
#             $nbhy = "­";          # \xAD, the soft-hyphen, also used by MS Word as non-break hyphen
#             $nbhy = "\\_";        # RTF non-break hyphen
#             $nbhy = "<ph>\_</ph>";# Trados might like this better???
#          }
#          s/ ([:»%\$€¥£])/$nbsp$1/g; # Make the space before :, », %, etc, non-breakable
#          s/([«]) /$1$nbsp/g;      # Make the space after « non-breakable
#          # Make the space before some units, when preceeded by a number, unbreakable;
#          # add all the units you want to this list!
#          s/(\d) (V|volts|ml|mm|cm)\b/$1$nbsp$2/g;
#          # Make the space before a 1 or 2 letter word, which is likely to be a unit,
#          # non-breakable; more general solution but might cover too many cases.
#          s/(\d) ([a-zA-Z]{1,2})\b/$1$nbsp$2/g;
#          # Make the hyphen in codes like A-2 non-breakable
#          s/\b([a-zA-Z0-9])-([a-zA-Z0-9])\b/$1$nbhy$2/g;
#          # Replace the soft hyphen (\xAD or alt-0173) by <ph>\_</ph> for Trados
#          s/­/<ph>\_</ph>/g; # Warning: there is a literal \xAD in utf8 here.
#         ' |

# Default is to just copy the input to the output.
cat
