#!/bin/bash
# $Id$
#############################################################
#
# @file postprocess_plugin
# @brief Default post-processor plugin
#
# @author Michel Simard
#
# COMMENTS:
#
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2010, Conseil national de recherches du Canada /
# Copyright 2010, National Research Council of Canada
#############################################################

## 
## Usage: postprocess_plugin < in > out
## 
## Default postprocessing plugin: to be called after detokenization.
##

if [ "$1" == "-help" -o "$1" == "-h" ]; then
    cat $0 | grep "^##" | cut -c4-
    exit 1
fi

exec cat

# Suggestion: for an English->French system, you could use fix-en-fr-numbers.pl
# to patch numbers, reformatting them from English to French style.
#exec fix-en-fr-numbers.pl
