#!/bin/bash
# $Id$
#############################################################
#
# @file preprocess_plugin
# @brief Default Preprocessing plugin
#
# @author Michel Simard
#
# COMMENTS:
#
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2010, Conseil national de recherches du Canada /
# Copyright 2010, National Research Council of Canada
#############################################################

## 
## Usage: preprocess_plugin SRC_LANG < in > out
## 
## Default preprocessing plugin, to be called prior to tokenization
##

if [ "$1" == "-help" -o "$1" == "-h" ]; then
    cat $0 | grep "^##" | cut -c4-
    exit 1
fi

test $# -eq 0 && echo "Missing language code argument" >&2 && exit 1
LANG=$1; shift

ridbom.sh | crlf2lf.sh

