#!/bin/bash
#
# @file preprocess_plugin
# @brief Default Preprocessing plugin
#
# @author Michel Simard
#
# COMMENTS:
#
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2010, Conseil national de recherches du Canada /
# Copyright 2010, National Research Council of Canada

## 
## Usage: preprocess_plugin SRC_LANG < in > out
## 
## Default preprocessing plugin, to be called prior to tokenization
##

if [[ $1 = -help || $1 = -h ]]; then
    cat $0 | grep "^##" | cut -c4-
    exit 1
fi

[[ $# = 0 ]] && echo "Missing language code argument" >&2 && exit 1
SOURCE_LANGUAGE=$1; shift

# Uncomment the following line to separate slash-separated words, or comment it
# out to leave them together:
FIX_SLASHES=1

# The following does minimalist preprocessing: remove the UTF8 bit-order mark,
# and convert newlines from the DOS to the Linux standard.
#ridbom.sh | crlf2lf.sh

# Clean up utf8 text: space, control characters, hyphens, etc
clean-utf8-text.pl |

# Optionally pre-tokenize around slashes:
if [[ $FIX_SLASHES ]]; then
   fix-slashes.pl
else
   cat
fi
