# Makefile for Portage adapt

# George Foster
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2014, Sa Majeste la Reine du Chef du Canada /
# Copyright 2014, Her Majesty in Right of Canada

OBJECTS = nnjm_native.o nnjm_abstract.o

LIBRARY = libportage_nn

TESTPROGS = test_portage_nnjm

PROGRAMS = $(TESTPROGS)

include ../build/Makefile.incl
