<?php
define ("__LOGO_REF__", "cs_temp_banner_e.jpg");
define ("__EMPTY_TEXT_AREA_WARNING__", "You have to enter a text to translate");
define ("__SWITCH_LANG_TEXT__", "Français");
define ("__SWITCH_LANG_REF__", "interface_fra.html");
define ("__TEXT_BOX_HEADER__", "Enter text to be translated:");
define ("__RADIO_LABEL_DIR_FR_EN__", "French / English");
define ("__RADIO_VALUE_DIR_FR_EN__", "a");
define ("__RADIO_LABEL_DIR_EN_FR__", "English / French");
define ("__RADIO_VALUE_DIR_EN_FR__", "b");
define ("__RADIO_LABEL_DIR_CH_EN__", "Chinese / English");
define ("__RADIO_VALUE_DIR_CH_EN__", "c");
define ("__BTN_LABEL_SUBMIT__", "Submit");
define ("__BTN_LABEL_RESET__", "Reset");
define ("__SITES_LIST_HEADER__", "Translate the chinese web page into English:");
define ("__SITE_A_VALUE__", "a");
define ("__SITE_A_HREF__", "www.pku.edu.cn");
define ("__SITE_A_TEXT__", "Peking University");
define ("__SITE_B_VALUE__", "b");
define ("__SITE_B_HREF__", "www.zju.edu.cn");
define ("__SITE_B_TEXT__", "Zhe Jiang University");
define ("__SITE_C_VALUE__", "c");
define ("__SITE_C_HREF__", "www.fudan.edu.cn");
define ("__SITE_C_TEXT__", "Fudan University");
define ("__SITE_D_VALUE__", "d");
define ("__SITE_D_HREF__", "www.bnu.edu.cn");
define ("__SITE_D_TEXT__", "Beijing Normal University");
define ("__SITE_E_VALUE__", "e");
define ("__SITE_E_HREF__", "www.nlc.gov.cn");
define ("__SITE_E_TEXT__", "National Library of China");
define ("__SITE_F_VALUE__", "f");
define ("__SITE_F_HREF__", "corpus/example.html.gb");
define ("__SITE_F_TEXT__", "Test file (GB2312)");
define ("__SITE_G_VALUE__", "g");
define ("__SITE_G_HREF__", "www.people.com.cn");
define ("__SITE_G_TEXT__", "People");
define ("__SITE_H_VALUE__", "h");
define ("__SITE_H_HREF__", "www.wforum.com/gbindex.html");
define ("__SITE_H_TEXT__", "WForum");
define ("__SITE_I_VALUE__", "i");
define ("__SITE_I_HREF__", "www.chinanewsagency.com");
define ("__SITE_I_TEXT__", "China news agency");
define ("__SITE_J_VALUE__", "j");
define ("__SITE_J_HREF__", "china.org.cn/chinese/index.htm");
define ("__SITE_J_TEXT__", "China.org.cn");
define ("__TRANSLATOR_ENGINE_NAME__", "Portage Translation Engine");
define ("__COPYRIGHTS_NOTE__", "&copy; 2005-2009, National Research Council Canada");
define ("__NEW_TRANSLATION_BTN__", "New Translation");
define ("__TRANSLATION_RESULT_TITLE__", "-- Translation result --");
define ("__TRANSLATION_RESULT_SRC_TITLE__", "Here's what you have typed:");
define ("__TRANSLATION_RESULT_TGT_TITLE__", "The result is:");
?>
