<?php
define ("__LOGO_REF__", "cs_temp_banner_f.jpg");
define ("__EMPTY_TEXT_AREA_WARNING__", "Il faut écrire un texte a traduire");
define ("__SWITCH_LANG_TEXT__", "English");
define ("__SWITCH_LANG_REF__", "interface_eng.html");
define ("__TEXT_BOX_HEADER__", "Tapez le texte à traduire :");
define ("__RADIO_LABEL_DIR_FR_EN__", "Français / Anglais");
define ("__RADIO_VALUE_DIR_FR_EN__", "a");
define ("__RADIO_LABEL_DIR_EN_FR__", "Anglais / Français");
define ("__RADIO_VALUE_DIR_EN_FR__", "b");
define ("__RADIO_LABEL_DIR_CH_EN__", "Chinois / Anglais");
define ("__RADIO_VALUE_DIR_CH_EN__", "c");
define ("__BTN_LABEL_SUBMIT__", "Soumettre");
define ("__BTN_LABEL_RESET__", "Réinitialiser");
define ("__SITES_LIST_HEADER__", "Traduire la page chinoise en anglais :");
define ("__SITE_A_VALUE__", "a");
define ("__SITE_A_HREF__", "www.pku.edu.cn");
define ("__SITE_A_TEXT__", "Université de Pékin");
define ("__SITE_B_VALUE__", "b");
define ("__SITE_B_HREF__", "www.zju.edu.cn");
define ("__SITE_B_TEXT__", "Université de Zhe Jiang");
define ("__SITE_C_VALUE__", "c");
define ("__SITE_C_HREF__", "www.fudan.edu.cn");
define ("__SITE_C_TEXT__", "Université de Fudan");
define ("__SITE_D_VALUE__", "d");
define ("__SITE_D_HREF__", "www.bnu.edu.cn");
define ("__SITE_D_TEXT__", "Université de Beijing Normal");
define ("__SITE_E_VALUE__", "e");
define ("__SITE_E_HREF__", "www.nlc.gov.cn");
define ("__SITE_E_TEXT__", "Bibliothèque Nationale de Chine");
define ("__SITE_F_VALUE__", "f");
define ("__SITE_F_HREF__", "corpus/example.html.gb");
define ("__SITE_F_TEXT__", "Document d'essai (GB2312)");
define ("__SITE_G_VALUE__", "g");
define ("__SITE_G_HREF__", "www.people.com.cn");
define ("__SITE_G_TEXT__", "People");
define ("__SITE_H_VALUE__", "h");
define ("__SITE_H_HREF__", "www.wforum.com/gbindex.html");
define ("__SITE_H_TEXT__", "WForum");
define ("__SITE_I_VALUE__", "i");
define ("__SITE_I_HREF__", "www.chinanewsagency.com");
define ("__SITE_I_TEXT__", "China news agency");
define ("__SITE_J_VALUE__", "j");
define ("__SITE_J_HREF__", "china.org.cn/chinese/index.htm");
define ("__SITE_J_TEXT__", "China.org.cn");
define ("__TRANSLATOR_ENGINE_NAME__", "Moteur de traduction Portage");
define ("__COPYRIGHTS_NOTE__", "&copy; 2005-2009, Conseil national de recherches Canada");
define ("__NEW_TRANSLATION_BTN__", "Nouvelle traduction");
define ("__TRANSLATION_RESULT_TITLE__", "Résultat de la traduction");
define ("__TRANSLATION_RESULT_SRC_TITLE__", "Voici ce que vous avez entré :");
define ("__TRANSLATION_RESULT_TGT_TITLE__", "Le résultat est :");
?>
