#!/bin/bash

# @file all-best-rr-vals 
# @brief Summarize a set of rescore-results files in directories below current
# one.
#
# @author George Foster / converted to bash by Eric Joanis
#
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2007, Sa Majeste la Reine du Chef du Canada /
# Copyright 2007, Her Majesty in Right of Canada


##
## all-best-rr-vals [DIR_PATTERN]
##
## Summarize a set of rescore-results files in directories below current one
## DIR_PATTERN should expand to the desired directories [*]
##

echo 'all-best-rr-vals, NRC-CNRC, (c) 2007 - 2008, Her Majesty in Right of Canada'

if [[ $# > 1 || $1 =~ ^-h ]]; then
   cat $0 | egrep '^##' | cut -c4-
   exit 1
fi

if [[ $# = 1 ]]; then
   pref="$1"
else
   pref="*"
fi

if ! ls -t1 $pref/rescore-results >& /dev/null; then
   echo `basename $0`: No files found matching $pref/rescore-results 
   exit 1
fi

for f in `ls -t1 $pref/rescore-results`; do
   best=`best-rr-val $f`
   log=`dirname $f`/log.cow
   if [[ -r $log ]]; then
      if grep -q "New model identical to previous one" $log; then
         status="(converged)"
      elif grep -q "No new sentences in the N-best lists" $log; then
         status="(converged)"
      elif grep -q "cow.sh fatal error" $log; then
         status="(crashed)"
      elif grep -q "Reached maximum number of iterations" $log; then
         status="(reached max iter)"
      fi
   fi
   echo "$best $status"
done

