#!/bin/bash

# @file all-best-rr-vals 
# @brief Summarize a set of rescore-results files in directories below current
# one.
#
# @author George Foster / converted to bash by Eric Joanis
#
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2007, Sa Majeste la Reine du Chef du Canada /
# Copyright 2007, Her Majesty in Right of Canada


##
## all-best-rr-vals [DIR_PATTERN]
##
## Summarize a set of rescore-results files in directories below current one
## DIR_PATTERN should expand to the desired directories [*]
##

# Includes NRC's bash library.
source `dirname $0`/sh_utils.sh

print_nrc_copyright all-best-rr-vals 2007


if [[ $1 =~ ^-h ]]; then
   cat $0 | egrep '^##' | cut -c4-
   exit 1
fi

if [[ $# -gt 1 ]]; then
   prefs=$*
else
   if [[ $# = 1 ]]; then
      prefs="$1"
   else
      prefs="*"
   fi
   if ! ls -t1 $prefs/rescore-results >& /dev/null; then
      echo `basename $0`: No files found matching $pref/rescore-results 
      exit 1
   fi
fi

for pref in $prefs; do
   file_list="$file_list $pref/rescore-results"
done

#echo file_list=$file_list

for f in `ls -t1 $file_list 2> /dev/null`; do
   best=`best-rr-val $f`
   log=`dirname $f`/log.cow
   if [[ -r $log ]]; then
      if grep -q "New model identical to previous one" $log; then
         status="(converged)"
      elif grep -q "No new sentences in the N-best lists" $log; then
         status="(converged)"
      elif grep -q "cow.sh fatal error" $log; then
         status="(crashed)"
      elif grep -q "Reached maximum number of iterations" $log; then
         status="(reached max iter)"
      fi
   fi
   echo "$best $status"
done
