#!/bin/bash

# @file best-rr-val 
# @brief Pick out the best line in a rescore-results file.
#
# @author George Foster / converted to bash by Eric Joanis
#
# Technologies langagieres interactives / Interactive Language Technologies
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2007, Sa Majeste la Reine du Chef du Canada /
# Copyright 2007, Her Majesty in Right of Canada

##
## best-rr-val [-w] rescore-results
##
## Pick out the best line in a rescore-results file.
## Note: Use all-best-rr-vals to loop over multiple experiments.
## 
## Options:
## -w  Print weights only, minus canoe switches [print bleu score only]
##


wts=0
if [[ $# > 0 && $1 = -w ]]; then
   wts=1
   shift
fi

if [[ $# = 0 || $1 =~ ^-h ]]; then
   cat $0 | egrep '^##' | cut -c4-
   exit 1
fi

if [[ ! -f $1 ]]; then
   echo `basename $0`: $1: No such file or directory
   exit 2
fi

if [[ $wts = 0 ]]; then
   bleu=`sort -k3,3 -gr $1 2> /dev/null | head -1 | cut -d' ' -f3`
   line=`grep -n "BLEU score: $bleu" $1 | head -1 | cut -d: -f1`
   nl=`wc -l < $1`
   echo "$bleu $1 ($nl iters, best = $line)"
else
   sort -k3,3 -gr $1 2> /dev/null | head -1 | cut -d' ' -f4- | perl -pe 's/-[a-zA-Z]+//go; s/:/ /go;'
fi
