#!/bin/bash
# $Id$

# @file time-mem
# @brief Map/Reduce wall/cpu time, VMEM & RAM.
#
# @author Samuel Larkin
#
# Technologies langagieres interactives / Interactive Language Technologiesm
# Inst. de technologie de l'information / Institute for Information Technology
# Conseil national de recherches Canada / National Research Council Canada
# Copyright 2009, Sa Majeste la Reine du Chef du Canada /
# Copyright 2009, Her Majesty in Right of Canada
 

# Includes NRC's bash library.
source `dirname $0`/sh_utils.sh

if [[ $PORTAGE_INTERNAL_CALL ]]; then WAS_CALLED_INTERNALLY=1; fi
[[ $PORTAGE_INTERNAL_CALL ]] ||
print_nrc_copyright "time-mem" 2009
export PORTAGE_INTERNAL_CALL=1


# Summarizes Wall/Cpu time, VMEM & RAM.
# If there is an argument, the output will mimic grep's output => filename:line
parseCommand() {
   ARG=$1
   declare line
   declare VMEM_LIST=0
   declare RAM_LIST=0
   declare CPU_TIME_LIST=0
   declare WALL_TIME=0

   # Single-job-total: Real 0.112s User 0.004s
   # 
   while read line
   do
      # Indicate that we are aware of this line.
      [[ $DEBUG ]] && echo -n "{> "
      echo $line

      # RP-Totals: Wall time 21s CPU time 40.03s Max VMEM 0.076G Max RAM 0.007G
      if [[ $line =~ "RP-Totals: Wall time ([0-9.]+)s CPU time ([0-9.]+)s Max VMEM ([0-9.]+)G Max RAM ([0-9.]+)G" ]]; then
         [[ $DEBUG ]] && echo "{Wall time> ${BASH_REMATCH[1]}"
         WALL_TIME_LIST="$WALL_TIME_LIST ${BASH_REMATCH[1]}"

         [[ $DEBUG ]] && echo "{CPU> ${BASH_REMATCH[2]}"
         CPU_TIME_LIST="$CPU_TIME_LIST ${BASH_REMATCH[2]}"

         [[ $DEBUG ]] && echo "{VMEM> ${BASH_REMATCH[3]}"
         VMEM_LIST="$VMEM_LIST ${BASH_REMATCH[3]}"

         [[ $DEBUG ]] && echo "{RAM> ${BASH_REMATCH[4]}"
         RAM_LIST="$RAM_LIST ${BASH_REMATCH[4]}"
      fi

      # Single-job-total: Real 0.092s User 0.028s Sys 0.000s PCPU 30.45%
      if [[ $line =~ "Single-job-total: Real ([0-9.]+)s User ([0-9.]+)s Sys ([0-9.]+)s" ]]; then
         [[ $DEBUG ]] && echo "{Real> ${BASH_REMATCH[1]}"
         WALL_TIME_LIST="$WALL_TIME_LIST ${BASH_REMATCH[1]}"

         # We include User & Sys for cpu time.
         [[ $DEBUG ]] && echo "{User> ${BASH_REMATCH[2]}"
         CPU_TIME_LIST="$CPU_TIME_LIST ${BASH_REMATCH[2]}"

         [[ $DEBUG ]] && echo "{Sys> ${BASH_REMATCH[3]}"
         CPU_TIME_LIST="$CPU_TIME_LIST ${BASH_REMATCH[3]}"
      fi
      # run_cmd rc=0 Max VMEM 0.071G Max RAM 0.009G
      if [[ $line =~ "run_cmd rc=0 Max VMEM ([0-9.]+)G Max RAM ([0-9.]+)G" ]]; then
         [[ $DEBUG ]] && echo "{VMEM> ${BASH_REMATCH[1]}"
         VMEM_LIST="$VMEM_LIST ${BASH_REMATCH[1]}"

         [[ $DEBUG ]] && echo "{RAM> ${BASH_REMATCH[2]}"
         RAM_LIST="$RAM_LIST ${BASH_REMATCH[2]}"
      fi

      # Find the overall wall time.
      if [[ $line =~ "Master-Wall-Time ([0-9.]+)s" ]]; then
         [[ $DEBUG ]] && echo "{Master-Wall-Time> ${BASH_REMATCH[1]}"
         # Master wall time was calculated for us, override.
         WALL_TIME_LIST="${BASH_REMATCH[1]}"
      fi
   done < <(egrep 'Single-job-total:|RP-Totals:|run_cmd rc=0|Master-Wall-Time')

   [[ $DEBUG ]] && echo "<D> parseCommand: $WALL_TIME : $CPU_TIME_LIST : $VMEM_LIST : $RAM_LIST" >&2

   MON_VSZ=`echo $VMEM_LIST | sum.pl -l -m`
   MON_RSS=`echo $RAM_LIST | sum.pl -l -m`
   CPU_TIME=`echo $CPU_TIME_LIST | sum.pl -l`
   WALL_TIME=`echo $WALL_TIME_LIST | sum.pl -l`

   RESULT="${ARG}TIME-MEM\tWALL TIME: ${WALL_TIME}s\tCPU TIME: ${CPU_TIME}s\tVSZ: ${MON_VSZ}G\tRSS: ${MON_RSS}G"
   [[ $DEBUG ]] && echo -e "<D> $RESULT" >&2
   sync
   echo -e $RESULT | second-to-hms.pl
}



# Combine all summary into one final summary.
reduce() {
   declare line
   declare VMEM_LIST=0
   declare RAM_LIST=0
   declare CPU_TIME_LIST=0
   declare WALL_TIME_LIST=0

   indent=">"
   while read line
   do
      [[ $DEBUG ]] && echo "<Dr> $line" >&2
      # Skip commented lines.
      if [[ $line =~ "^(\./)?([^>]+):((P-RES-MON|TIME-MEM)>WALL TIME: ([0-9.]+)s>CPU TIME: ([0-9.]+)s>VSZ: ([0-9.]+)G>RSS: ([0-9.]+)G)" ]]; then
         echo -e "$indent${BASH_REMATCH[2]}:${BASH_REMATCH[3]}"
         WALL_TIME_LIST=" $WALL_TIME_LIST ${BASH_REMATCH[5]}"
         CPU_TIME_LIST="$CPU_TIME_LIST ${BASH_REMATCH[6]}"
         VMEM_LIST="$VMEM_LIST ${BASH_REMATCH[7]}"
         RAM_LIST="$RAM_LIST ${BASH_REMATCH[8]}"
      elif [[ $line =~ "(P-RES-MON|TIME-MEM)>WALL TIME:" ]]; then
         echo -e "$indent$line"
      fi
   done

   [[ $DEBUG ]] && echo "DEBUG reduce: $WALL_TIME_LIST : $CPU_TIME_LIST : $VMEM_LIST : $RAM_LIST" >&2

   MON_VSZ=`echo $VMEM_LIST | sum.pl -l -m`
   MON_RSS=`echo $RAM_LIST | sum.pl -l -m`
   CPU_TIME=`echo $CPU_TIME_LIST | sum.pl -l`
   WALL_TIME=`echo $WALL_TIME_LIST | sum.pl -l`

   RESULT="TIME-MEM\tWALL TIME: ${WALL_TIME}s\tCPU TIME: ${CPU_TIME}s\tVSZ: ${MON_VSZ}G\tRSS: ${MON_RSS}G"
   [[ $DEBUG ]] && echo -e "<D> $RESULT" >&2
   echo -e $RESULT
}



TIMEFORMAT="Single-job-total: Real %3Rs User %3Us Sys %3Ss PCPU %P%%"
WORKDIR_ABSOLUTE=/tmp
run_cmd() {
   if [[ "$1" = "-no-error" ]]; then
      shift
      RUN_CMD_NO_ERROR=1
   else
      RUN_CMD_NO_ERROR=
   fi
   (( $VERBOSE > 0 )) && date >&2
   (( $VERBOSE > 0 )) && echo "$@" >&2
   if [[ ! $NOTREALLY ]]; then
      START_TIME=`date +"%s"`
      MON_FILE=`mktemp $WORKDIR_ABSOLUTE/mon.run_cmd.XXXXXXXX`
      trap "rm -f $MON_FILE; exit" 0
      for signal in 1 2 3 5 10 13 14 15; do
         trap "rm -f $MON_FILE; exit $((128 + signal))" $signal
      done
      process-memory-usage.pl -s 1 30 $$ > $MON_FILE &
      MON_PID=$!
      # We don't consider calls via time-mem as internal, so unexport
      # PORTAGE_INTERNAL_CALL unless it was set before time-mem was called.
      [[ $WAS_CALLED_INTERNALLY ]] || export -n PORTAGE_INTERNAL_CALL
      time {
         # time this block as a whole so that sync (below) can be effective
         # before the output of time itself is printed to STDERR
         eval "$@"
         rc=$?
         sync
      }
      export PORTAGE_INTERNAL_CALL=1
      kill -10 $MON_PID
      sync
      echo "run_cmd finished (rc=$rc): $@" >&2
      if [ -s "$MON_FILE" -a $(( `wc -l < $MON_FILE` > 1 )) ]; then
         MON_VSZ=`egrep -ho 'vsz: [0-9.]+G' $MON_FILE 2> /dev/null | egrep -o "[0-9.]+" | sum.pl -m`
         MON_RSS=`egrep -ho 'rss: [0-9.]+G' $MON_FILE 2> /dev/null | egrep -o "[0-9.]+" | sum.pl -m`
         echo "run_cmd rc=$rc Max VMEM ${MON_VSZ}G Max RAM ${MON_RSS}G" >&2
      fi
      END_TIME=`date +%s`
      WALL_TIME=$((END_TIME - START_TIME))
      echo "Master-Wall-Time ${WALL_TIME}s" >&2

      if [[ -z "$RUN_CMD_NO_ERROR" && "$rc" != 0 ]]; then
         [[ $DEBUG ]] && echo "Oups there was an error." >&2
         (( $VERBOSE > 0 )) && echo "Exit status: $rc is not zero - aborting." >&2
         exit $rc
      fi
   fi
}



usage() {
   for msg in "$@"; do
      echo $msg >&2
   done
   cat <<==EOF== >&2

Usage: time-mem [options] {cmd | files}

  Map/Reduce Wall/CPU time, VMEM & RAM.

  Map mode: by default, runs the command provided on the command line,
  measuring CPU and memory usage.

  Reduce mode: with the -Tally option, tallies results from previous runs, in
  which case the arguments should be a list of log files to process.

Options:

  -T(ally)      Tally results.
  -m(eta) NAME  Label the tally line with NAME, e.g., for hierarchical reports.
  -h(elp)       print this help message
  -v(erbose)    increment the verbosity level by 1 (may be repeated)
  -d(ebug)      print debugging information

==EOF==

   exit 1
}

# Command line processing [Remove irrelevant parts of this code when you use
# this template]
VERBOSE=0
TALLY=
while [ $# -gt 0 ]; do
   case "$1" in
   #-m|-meta)            META=1;;
   -m|-meta)            META=$2;shift;;
   -T|Tally)            TALLY=1;;
   -v|-verbose)         VERBOSE=$(( $VERBOSE + 1 ));;
   -d|-debug)           DEBUG=1;;
   -h|-help)            usage;;
   --)                  shift; break;;
   -*)                  error_exit "Unknown option $1.";;
   *)                   break;;
   esac
   shift
done

# Escape arguments that might have a space in them.
declare -a ARGUMENTS;
ARGUMENTS=( "$@" )
for ((i=0;i<${#ARGUMENTS};i++)); do
   if [[ ${ARGUMENTS[$i]} =~ " " ]]; then
      ARGUMENTS[$i]="\"${ARGUMENTS[$i]}\"";
   fi
done


# If there is no argument, there is nothing to do.
[[ ${#ARGUMENTS[@]} == 0 ]] && exit 0;

# Make sure we detect failure in a serie of pipes.
set -o pipefail;

pgm=`basename $1`

# The user specified -T(ally): they want a one line summary for each log file
# provided
if [[ $TALLY ]]; then
   [[ $META ]] && META="$META:"
   { for f in $*; do
      [[ $DEBUG ]] && echo "Processing $f" >&2
      g=`basename $f`
      if ! { set -o pipefail; egrep -h 'P-RES-MON|TIME-MEM' $f | sed "s/^P-RES-MON\|TIME-MEM/${g}:TIME-MEM/"; }; then
         [[ $DEBUG ]] && echo "Calculating on the fly" >&2
         cat $f \
         | second-to-hms.pl -r \
         | parseCommand "$f:"
      fi
   done } \
   | second-to-hms.pl -r \
   | perl -pe 'while (s/^(>*)   /$1>/) {1}; s/\t/>/g' \
   | reduce \
   | perl -pe 'while (s/^(>*)>/$1   /) {1}; s/>/\t/g;
               s/^P-RES-MON|^TIME-MEM/'"${META}"'TIME-MEM/;' \
   | second-to-hms.pl

# Check if the command is a known executable that already produces time & mem data.
elif [[ $pgm == "rat.sh" || $pgm == "cat.sh" || $pgm == "cow.sh" || $pgm == "gen-jpt-parallel.sh" || $pgm == "canoe-parallel.sh" ]]; then
   [[ $DEBUG ]] && echo "Parsing command $pgm" >&2
   # These commands already produce the data, we only need to parse the data.
   { { eval "${ARGUMENTS[@]}" || exit; sync; } 3>&1 1>&2 2>&3 || exit | parseCommand 2>&1; sync; } 3>&1 1>&2 2>&3

# The user wants to time a command that doesn't produce statistics and he's
# asking us calculate the statistics for him.
else
   if [[ $DEBUG ]]; then
      # We need to warn the debugger both on stdout & stderr that this script
      # is screwing up the streams.
      {
         echo "WARNING: Debug mode messes with stderr & stdout."
         echo "<D> cmd: ${ARGUMENTS[@]}";
      } | tee /dev/stderr
   fi
   # Here we want the original stdout as pass-through and we want to process
   # the original stderr.
   { { run_cmd "${ARGUMENTS[@]}" || exit; sync; } 3>&1 1>&2 2>&3 || exit | parseCommand 2>&1; sync; } 3>&1 1>&2 2>&3
fi

