TEMP_FILES=corpora istraining.lock log.* queue queue.lock witness models \
           incremental-update.lock incr-update.status src_block_* tgt_block_*
TEMP_DIRS=incremental-tmp.*
include ../Makefile.incl
